config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :tracks
  resources :albums
  resources :artists
  resources :home

  root 'home#home'
  get 'contact', to:'home#contact'
  post 'request_contact', to: 'home#request_contact'
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base

#artist belongs to a user and a genre. 
#a artist can have many albums and are dependent on artist
#validation are set on title and genre so that user has to include these details

	belongs_to :user
	belongs_to :genre
	has_many :albums, dependent: :destroy
	validates :title, presence: true
    validates :title, uniqueness: true
    validates :genre, presence: true

    has_attached_file :artist_img, styles: { artist_index: "150x250>", artist_show: "225x375>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :artist_img, content_type: /\Aimage\/.*\Z/
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! #user has to be signed in in order to access artists


  def index
    #if the genre is not selected then all the artists will be displayed
    if params[:genre].blank?
      @artists = Artist.all.order("created_at DESC")
    else
      #else when a genre is selected only the artist belonging to that genre is displayed
      @genre_id = Genre.find_by(name: params[:genre]).id
      @artists = Artist.where(:genre_id => @genre_id).order("created_at DESC")
    end
  end


  def show
  end


  def new
    #crete a artist and assign it to the current user and also the genre of the artist
    @artist = current_user.artists.build
    @genre = Genre.all.map{ |g| [g.name, g.id]}
  end

  def edit
    @genre = Genre.all.map{ |g| [g.name, g.id]}
  end


  def create
    @artist = current_user.artists.build(artist_params)
    @artist.genre_id = params[:genre_id]

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @artist.genre_id = params[:genre_id]
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.js { flash[:notice] = 'Artist was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    #all the artist fields are permitted 
    def artist_params
      params.require(:artist).permit(:title, :biography, :genre_id, :artist_img)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= simple_form_for @artist, :html => { :multipart => true }  do |f| %>
	<%= select_tag(:genre_id, options_for_select(@genre), :prompt => t('.select_genre')) %>
	<%= f.file_field :artist_img%>
	<%= f.input :title, label: t('.artist_name') %>
	<%= f.input :biography %>	 
	<%= f.button :submit %>
<% end %>

<!-- This form will be rendered when a user wants to create a new artist -->

app/views/artists/destroy.js.erb
$('#artist_<%= @artist.id %>').hide();

app/views/artists/edit.html.erb
<h1> <%= t('.edit_artist') %></h1>

<%= simple_form_for @artist, :html => { :multipart => true } do |f| %>
  <%= f.select :genre_id, @genre %>
  <%= f.file_field :artist_img%>
  <%= f.input :title, label: t('.artist_name') %>
  <%= f.input :biography %>
 
  <%= f.button :submit %>

<% end %>

<%= link_to t('.show'), @artist, class: "btn btn-default" %> 
<%= link_to t('.back'), artists_path, class: "btn btn-default" %>

<!-- The form is not rendered when user wants to edit. This is because select genre should load the genre of the artist that requires changing. Rendering a form would not have made this possible -->

app/views/artists/index.html.erb
<h1 class="current-genre"><%= params[:genre]%></h1>

<% if @artists.count == 0 %>
  <h1><%=t('.h1')%></h1>
<% else %>

  <table class="table">
    <thead>
      <tr>
        <th><%=t('.artist_image')%></th>
        <th><%=t('.artist_title')%></th>
        <th><%=t('.artist_bio')%></th>
        <th><%=t('.artist_genre')%></th>

        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @artists.each do |artist| %>

        <tr id='<%="artist_#{artist.id}"%>'>

          <!-- Image of the artist is displayed in the form column -->

          <td> <a href="/artists/<%= artist.id %>"><%= image_tag artist.artist_img.url(:artist_index), class: "artist"%></a></td>
          <td><%= artist.title %></td>
          <td><%= artist.biography %></td>
          <td><%= artist.genre.name %></td>
          <td><%= link_to t('.show'), artist, class: "btn btn-default" %></td>

          <!-- The user that is signed in can only edit and destroy artist that they created. -->

          <% if user_signed_in?%>
            <% if current_user.id == artist.user_id %>
              <td><%= link_to t('.edit'), edit_artist_path(artist), class: "btn btn-default" %> </td> 
              <td><%= link_to t('.destroy'),artist, :method => :delete, :data => { :confirm => 'Are you sure?' }, :remote => true, class: "btn btn-default" %></td>
            <% end %>
          <% end %>     
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/artists/new.html.erb
<h1><%=t('.new_artist')%></h1>

<%= render 'form' %>

<!-- form is rendered here from _form.html.erb -->

<%= link_to t('.back'), artists_path , class: "btn btn-default"%>

app/views/artists/show.html.erb
<div class="row">
	<div class="col-md-4">
		<%= image_tag @artist.artist_img.url(:artist_show), class: "artist-show"%>
	</div>
	<div class="col-md-8">
		<p>
		  <strong><%= t('.artist_title') %></strong>
		  <%= @artist.title %>
		</p>
		<p>
		  <strong><%= t('.artist_bio') %></strong>
		  <%= @artist.biography %>
		</p>
		<p> <%= t('.album') %></p>
		<table class="table">
			<% @artist.albums.each do |album| %>
			  <tr id='<%="album_#{album.id}"%>'>
					<td><%= album.title%></td>
					<td><%= link_to t('.show'),album , class: "btn btn-default"%></td>

					<!-- A user will be able to edit adn destroy only if their user id matches the current user id -->

					<% if user_signed_in?%>
						<% if @artist.user_id == current_user.id %>
					        <td><%= link_to t('.edit'), edit_album_path(album), class: "btn btn-default" %></td>
							<td><%= link_to t('.destroy'),album, :method => :delete, :data => { :confirm => 'Are you sure?' }, :remote => true , class: "btn btn-default"%></td>
							<!--  The album is destroyed remotely and the table data is hidden. -->

						<% end %>
					<% end %>
			  </tr>
			  <%end%>
		</table>

		<!-- Again the user id of the artist has to be equal to the current user id to add a album to an artist -->
		<% if user_signed_in?%>
			<% if @artist.user_id == current_user.id %>	
				<p><%= link_to t('.add_album'), new_album_path(artist_id: @artist), class: "btn btn-default" %></p>
			<%end%>
		<%end%>


	</div>
</div>

<%= link_to t('.back'), artists_path , class: "btn btn-default"%>