config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :tracks
  resources :albums
  resources :artists
  resources :home

  root 'home#home'
  get 'contact', to:'home#contact'
  post 'request_contact', to: 'home#request_contact'
  

end

app/views/shared/_footer.html.erb
<footer class="navbar-fixed-bottom">
	<div class="container text-center">
		<p class="text-muted"> &copy; Created by Kusal Gurung <%= Time.now.year%> </p> 
	</div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to t('.musify'), root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li> <%= link_to t('.artists'), artists_path %> </li>
      <li> <%= link_to t('.albums'), albums_path %> </li>
      <li> <%= link_to t('.tracks'), tracks_path %> </li>
      <li> <%= link_to t('.contact_us'), contact_path %> </li>
      <li> <%= link_to t('.sign_up'), new_user_registration_path %> </li>

      <!-- if the user is signed in then a profile and signout links will appear on the navigation bar or else a signout button will appear -->

      <% if user_signed_in? %>
        <li><%= link_to t('.profile'), edit_user_registration_path %></li>
        <li><%= link_to t('.sign_out'), destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li> <%= link_to t('.sign_in'), new_user_session_path %> </li> 
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Genres<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Genre.all.each do |genre|%>
              <li>
                <%= link_to genre.name, artists_path(genre: genre.name), class: "link"%>
              </li>
            <% end %>
          </ul>
        </li>      

      <!-- This is the right hand side of the navigation bar. A new artist can only be created when a user is signed in -->

      <% if user_signed_in? %>
        <li><%= current_user.email %></li>
        <li> <%= link_to t('.new_artist'), new_artist_path%> </li>
        
      <% end %>
    
    </ul>
  </div>
</nav>

<p id="notice"><%= notice%></p>
<p id="alert"><%= alert %></p>