config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :tracks
  resources :albums
  resources :artists
  resources :home

  root 'home#home'
  get 'contact', to:'home#contact'
  post 'request_contact', to: 'home#request_contact'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def home
    #in order to display all track, album and artist in homepage.
    @tracks = Track.all;
    @albums = Album.all
    @artists = Artist.all

  end

  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end

    redirect_to root_path
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.haml
%h1= t('.title')
%p= t('.contact_us')
= form_tag request_contact_path, method: 'post' do
	= label_tag :name, t('.name')
	= text_field_tag :name, '', title: t('.enter_name'), size: 20

	= label_tag :email, t('.email')
	= email_field_tag :email, '', title: t('.enter_email')

	= label_tag :telephone, t('.telephone')
	= telephone_field_tag :telephone, '', title: t('.enter_telephone')

	= label_tag :message, t('.message')
	= text_field_tag :message, '', title: t('.enter_message'), size: 50

	= submit_tag t('.submit'), class: "btn btn-default" 

		

app/views/home/home.html.haml
.row
	%h1= t('.title')

	%h2= t('.welcome')

	%h3= t('.message')

- 2.times do
	%br

.row
	.col-md-2			
		%strong= t('.artist') 
		%table.table 
			%thead 
				%tr
					%th= t('.artist_h1') 
			%tbody
				- @artists.each do |artist| 
					%tr
						%td= artist.title 
	.col-md-4
		%strong= t('.album')   
		%table.table 
			%thead
				%tr
					%th= t('.album_h1') 
					%th= t('.artist_h2') 
			%tbody
				- @albums.each do |album| 
					%tr
						%td= album.title 
						%td= album.artist.title

	.col-md-6
		%strong= t('.track') 
		%table.table 
			%thead
				%tr
					%th= t('.track_h1') 
					%th= t('.album_h2') 
					%th= t('.artist_h3') 
			%tbody
				- @tracks.each do |track| 
					%tr
						%td= track.title 
						%td= track.album.title
						%td= track.album.artist.title
					
				
				
		  