config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :tracks
  resources :albums
  resources :artists
  resources :home

  root 'home#home'
  get 'contact', to:'home#contact'
  post 'request_contact', to: 'home#request_contact'
  

end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to :artist
  has_many :tracks, dependent: :destroy
  validates :title, :artist, presence: true
  validates :title, presence: true
  validates :title, uniqueness: true

  #enables users to attach a image file to albums 

  has_attached_file :album_img, styles: { album_index: "150x250>", album_show: "225x375>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :album_img, content_type: /\Aimage\/.*\Z/
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :set_artist, only: [:new, :create]
  before_action :authenticate_user!

  #user needs to be authenticated in order to view the albums, artists and tracks
  def index
    @albums = Album.all.order("created_at DESC")
    #displays the albums in descending order
  end


  def show
  end

  def new
    @album = @artist.albums.new
  end

  def edit
  end

  def create
    @album = @artist.albums.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.js { flash[:notice] = 'Album was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private

    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:artist_id, :title, :album_img)
    end

    def set_artist
      @artist = Artist.find_by(id: params[:artist_id]) ||
      Artist.find(album_params[:artist_id])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
    <%= f.file_field "album_img"%>
        
    <%= f.label :artist_id %>
    <p><%= @album.artist.title %></p>
    <%= f.hidden_field :artist_id, value: @album.artist.id %>
    <%= f.label :title %>
    <%= f.text_field :title %>
       
    <%= f.submit %>
<% end %>

app/views/albums/destroy.js.erb
$('#album_<%= @album.id %>').hide();

app/views/albums/edit.html.erb
<h1><%= t('.edit_album')%></h1>

<%= render 'form' %>

<%= link_to t('.show'), @album, class: "btn btn-default" %> |
<%= link_to t('.back'), albums_path, class: "btn btn-default" %>

app/views/albums/index.html.erb
<h1><%= t('.list_album')%></h1>
<table class="table">
  <thead>
    <tr>
      <th><%=t('.album_image')%></th>
      <th><%=t('.artist')%></th>
      <th><%=t('.title')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr id='<%="album_#{album.id}"%>'>
        <td> <a href="/albums/<%= album.id %>"><%= image_tag album.album_img.url(:album_index), class: "artist"%></a></td>
        <td><%= album.artist.title%></td>
        <td><%= album.title %></td>
        <td><%= link_to t('.show'), album, class: "btn btn-default" %></td>

        <!-- A user with the same album user id as the current user id is allowed to edit and delete the albums or only the show page link will be visible -->

        <% if user_signed_in?%>
          <% if current_user.id == album.artist.user_id %>
            <td><%= link_to t('.edit'), edit_album_path(album), class: "btn btn-default" %></td>
            <td><%= link_to t('.destroy'), album, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-default"%></td>
            <%end%>
        <%end%>    
      </tr>  
    <% end %>
  </tbody>
</table>

<br>

app/views/albums/new.html.erb
<h1><%= t('.new_album') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), albums_path, class: "btn btn-default" %>

app/views/albums/show.html.erb
<p>
  <strong><%= t('.artist') %></strong>
  <%= @album.artist.title %>
</p>

<p>
  <strong><%= t('.title')%></strong>
  <%= @album.title %>
</p>

<table class="table">
	<% @album.tracks.each do |track| %>
	  <tr id='<%="track_#{track.id}"%>'>
		<td><%= link_to track.title, track %></td>

		<!-- Only the user with the same user id as the current user id will be able to edit and destroy the tracks belonging to an album -->

		<% if user_signed_in? %>
	        <% if track.album.artist.user_id == current_user.id %>
				<td><%= link_to t('.edit_track'), edit_track_path(track), class: "btn btn-default" %></td>
				<td><%= link_to t('.destroy_track'),track, :method => :delete, :data => { :confirm => 'Are you sure?' }, :remote => true, class: "btn btn-default" %></td>
			<% end %>
	        <% end %>
	  </tr>
	  <%end%>
</table> 

<% if user_signed_in? %>
	<% if @album.artist.user_id == current_user.id %>
		<%= link_to t('.add_track'), new_track_path(album_id: @album), class: "btn btn-default" %> |
		<%= link_to t('.edit_album'), edit_album_path(@album), class: "btn btn-default" %> |
	<% end %>
<% end %>


<%= link_to t('.back'), albums_path, class: "btn btn-default" %>